import Link from 'next/link';
import { redirect } from 'next/navigation';
import { requestPasswordReset, resendConfirmation, signIn } from './actions';
import { CheckoutSubmitButton } from '@/app/checkout/submit-button';
import '../managed.css';
export const metadata = { title:'Cuenta de administrador', robots:{index:false,follow:false} };
export default async function AuthPage({searchParams}:{searchParams:Promise<{mode?:string;error?:string;message?:string;next?:string}>}){
  const params=await searchParams;
  if(params.mode==='signup') redirect('/registro');
  const next=params.next??'/dashboard';
  return <main className="managedLogin"><Link href="/" className="managedBrand">NIVAL <span>PAY</span></Link><section className="managedLoginCard"><span className="managedEyebrow">CUENTA DE ADMINISTRADOR</span><h1>Tu panel.<br/>Todos tus negocios.</h1><p>Registra negocios y administra sus tarjetas.</p>{params.error&&<p className="managedError managedLoginMessage" role="alert">{params.error}</p>}{params.message&&<p className="managedSuccess managedLoginMessage" role="status">{params.message}</p>}<form action={signIn} className="managedForm"><input type="hidden" name="next" value={next}/><label>Correo<input name="email" type="email" autoComplete="email" required/></label><label>Contraseña<input name="password" type="password" autoComplete="current-password" required/></label><CheckoutSubmitButton className="managedSubmit" pendingLabel="Entrando…">Entrar a mi panel</CheckoutSubmitButton></form><Link href="/registro" className="managedRegisterLink">Crear mi cuenta <span>↗</span></Link><details className="managedLoginHelp"><summary>¿Olvidaste tu contraseña?</summary><form action={requestPasswordReset} className="managedForm"><label>Correo de tu cuenta<input name="email" type="email" autoComplete="email" required/></label><CheckoutSubmitButton className="managedSubmit" pendingLabel="Enviando…">Enviar enlace de recuperación</CheckoutSubmitButton></form></details><details className="managedLoginHelp"><summary>¿Falta confirmar tu correo?</summary><form action={resendConfirmation} className="managedForm"><input type="hidden" name="next" value={next}/><label>Correo de tu cuenta<input name="email" type="email" autoComplete="email" required/></label><CheckoutSubmitButton className="managedSubmit" pendingLabel="Enviando…">Reenviar confirmación</CheckoutSubmitButton></form></details></section><Link href="/negocio" className="managedAdminLink">Tengo un código de negocio →</Link><Link href="/" className="managedAdminLink">← Volver al inicio</Link></main>;
}
