'use client';
import { useState } from 'react';
import { PaymentPageView } from '@/app/pay/[token]/payment-page-view';

type Step = 'intro'|'pay-edit'|'pay-view'|'reviews-edit'|'reviews-view'|'wifi-edit'|'wifi-view'|'done';
const steps:Step[]=['intro','pay-edit','pay-view','reviews-edit','reviews-view','wifi-edit','wifi-view','done'];
const labels:Record<Step,string>={intro:'Empezar', 'pay-edit':'1 · Configura Pay','pay-view':'Pay: vista cliente','reviews-edit':'2 · Conecta Reseñas','reviews-view':'Reseñas: vista cliente','wifi-edit':'3 · Prepara WiFi','wifi-view':'WiFi: vista cliente',done:'Listo'};
export function CardsDemo(){
  const [step,setStep]=useState<Step>('intro');
  const [name,setName]=useState('Tu negocio'); const [holder,setHolder]=useState('Nombre de ejemplo'); const [bank,setBank]=useState('Banco de ejemplo'); const [clabe,setClabe]=useState('000000000000000000'); const [concept,setConcept]=useState('Consumo');
  const [reviewUrl,setReviewUrl]=useState(''); const [wifiUrl,setWifiUrl]=useState(''); const [notice,setNotice]=useState('');
  const index=steps.indexOf(step); const next=()=>{setStep(steps[Math.min(index+1,steps.length-1)]);setNotice('')}; const back=()=>{setStep(steps[Math.max(0,index-1)]);setNotice('')};
  const profile={business_name:name.trim()||'Tu negocio',brand_color:'#18784c',account_holder:holder,bank_name:bank,clabe:clabe||'000000000000000000',concept,holder_visible:true,bank_visible:true,clabe_visible:true,concept_visible:true,custom_sections:[]};
  const isEdit=step.endsWith('edit');
  const coach:Record<Step,{title:string;body:string}>={intro:{title:'Empieza aquí',body:'Haz clic en Siguiente para conocer Toke paso por paso.'},'pay-edit':{title:'Configura Pay',body:'Prueba los campos de esta pantalla. Cambia el nombre, beneficiario, banco, CLABE o concepto y mira cómo se actualiza la vista.'},'pay-view':{title:'Pruébalo como cliente',body:'Haz clic en un dato para copiarlo. Así se usa Pay cuando alguien acerca su teléfono a tu tarjeta.'},'reviews-edit':{title:'Conecta Reseñas de Google',body:'Pega aquí el enlace de reseñas de tu negocio. En el panel real este es el enlace que abrirá la tarjeta.'},'reviews-view':{title:'Mira la experiencia del cliente',body:'Esta es la salida hacia Reseñas de Google. Continúa cuando hayas visto qué ocurrirá al acercar el teléfono.'},'wifi-edit':{title:'Prepara WiFi',body:'Agrega el acceso de la red que quieres compartir con tus clientes.'},'wifi-view':{title:'Mira la experiencia del cliente',body:'Así verá el cliente el acceso al WiFi después de acercar su teléfono.'},done:{title:'Recorrido terminado',body:'Ya viste Pay, Reseñas de Google y WiFi. Puedes crear tu cuenta para configurarlos con datos reales.'}};
  return <div className="nv4Walkthrough"><div className="nv4DemoProgress"><span>RECORRIDO GUIADO · {index+1} DE {steps.length}</span><div role="progressbar" aria-label="Progreso de la demo" aria-valuenow={index+1} aria-valuemin={1} aria-valuemax={steps.length}><i style={{width:`${((index+1)/steps.length)*100}%`}}/></div></div>
    <div className="nv4DemoLayout"><aside className="nv4DemoSidebar"><strong>Toke <small>por Nival Tech</small></strong><span className="nv4DemoBusiness">{name||'Tu negocio'}</span><ol>{steps.map((item,i)=><li key={item} className={step===item?'active':''}><button type="button" onClick={()=>{setStep(item);setNotice('')}} aria-current={step===item?'step':undefined}><span>{i+1}</span>{labels[item]}</button></li>)}</ol><p>Demo local. Puedes probar los campos sin crear cuenta; nada se guarda.</p></aside>
    <div className="nv4DemoMain"><div className="nv5Coach"><span className="nv5CoachPointer" aria-hidden="true">↓</span><div><b>{coach[step].title}</b><p>{coach[step].body}</p></div><small>PASO {index+1}/{steps.length}</small></div><div className="nv4DemoTop"><span>PANEL DEL NEGOCIO · DEMOSTRACIÓN</span><span>Sin conexión a tu cuenta</span></div>
      <div className="nv4DemoIntro"><span className="nv2Eyebrow">{step==='intro'?'ANTES DE EMPEZAR':step==='done'?'LISTO PARA PROBAR':isEdit?'ASÍ LO CONFIGURA EL DUEÑO':'ASÍ LO VE TU CLIENTE'}</span><h2>{step==='intro'?'Vamos a crear tu tarjeta, paso por paso.':step==='pay-edit'?'Nival Pay: agrega cómo te pagan.':step==='pay-view'?'Así copia tus datos el cliente.':step==='reviews-edit'?'Nival Reseñas: conecta Google.':step==='reviews-view'?'El cliente llega a Google.':step==='wifi-edit'?'Nival WiFi: configura el acceso.':step==='wifi-view'?'El cliente abre el acceso al WiFi.':'Ya conoces las tres partes.'}</h2><p>{step==='intro'?'Primero editarás lo que ve el cliente. Después probarás cada acceso. Esta demo usa los mismos campos del panel actual y datos ficticios.':step==='pay-edit'?'El dueño edita beneficiario, banco, CLABE y concepto en la vista de Pay. Aquí se usa el mismo componente de edición que en el panel.':step==='pay-view'?'Al tocar los datos en la página pública, se copian. El cliente hace la transferencia desde su propia app bancaria.':step==='reviews-edit'?'En el panel se pega el enlace directo de reseñas de Google. El QR y la tarjeta pueden llevar al cliente a ese enlace.':step==='reviews-view'?'La página de Nival Reseñas redirige al enlace de Google que configuró el negocio; no redacta ni publica reseñas automáticamente.':step==='wifi-edit'?'El panel actual pide un enlace HTTPS de acceso al WiFi. La configuración de red y contraseña dentro del panel todavía no está disponible.':step==='wifi-view'?'El acceso abre la página configurada para tu red. El teléfono puede pedir confirmación antes de conectarse.':'Ahora puedes registrarte y probarlo con la información de tu negocio.'}</p></div>
      {step==='intro'&&<div className="nv4IntroTiles"><div><b>01</b><strong>Pay</strong><span>Comparte datos de cobro</span></div><div><b>02</b><strong>Reseñas</strong><span>Conecta tu enlace de Google</span></div><div><b>03</b><strong>WiFi</strong><span>Comparte el acceso a tu red</span></div></div>}
      {step==='pay-edit'&&<div className="nv4EditorGrid"><label className="nv4DemoField">Nombre del negocio<input value={name} onChange={e=>setName(e.target.value)} maxLength={45}/></label><div className="nv4DemoPay"><PaymentPageView embedded profile={profile} editor={{holder,bank,clabe,concept,paymentUrl:'',trialMode:true,demo:true,onHolder:setHolder,onBank:setBank,onClabe:setClabe,onConcept:setConcept,onPaymentUrl:()=>{}}}/></div></div>}
      {step==='pay-view'&&<div className="nv4DemoPublic"><PaymentPageView embedded profile={profile}/></div>}
      {step==='reviews-edit'&&<div className="nv4FormView"><div><label className="nv4DemoField">Enlace de reseñas de Google<input type="url" value={reviewUrl} onChange={e=>setReviewUrl(e.target.value)} placeholder="https://g.page/r/..."/></label><small>Cómo se hace hoy: pegas el enlace en Nival Reseñas y lo guardas desde tu panel. Aquí no lo guardamos.</small></div><div className="nv4DemoSimple"><span className="nv4DemoIcon">☆</span><strong>Nival Reseñas</strong><p>{reviewUrl?'Enlace agregado para esta simulación.':'Agrega el enlace para preparar este acceso.'}</p></div></div>}
      {step==='reviews-view'&&<div className="nv4DemoSimple"><span className="nv4DemoIcon">☆</span><strong>Abre las reseñas de {name||'tu negocio'}</strong><p>{reviewUrl?'El enlace configurado abriría Google. No redirigimos desde esta demo.':'En el panel real, primero debes pegar y guardar tu enlace de Google.'}</p><span className="nv4DemoDisabled">Continuar a Google al configurar el enlace ↗</span></div>}
      {step==='wifi-edit'&&<div className="nv4FormView"><div><label className="nv4DemoField">Enlace HTTPS de acceso al WiFi<input type="url" value={wifiUrl} onChange={e=>setWifiUrl(e.target.value)} placeholder="https://wifi.tunegocio.com/acceso"/></label><small>Es el campo disponible hoy en Nival WiFi. En esta demo no se guarda ni se genera un QR real.</small></div><div className="nv4DemoSimple"><span className="nv4DemoIcon">⌁</span><strong>Nival WiFi</strong><p>{wifiUrl?'Enlace agregado para esta simulación.':'Agrega el enlace de tu red para preparar el acceso.'}</p></div></div>}
      {step==='wifi-view'&&<div className="nv4DemoSimple"><span className="nv4DemoIcon">⌁</span><strong>WiFi de {name||'tu negocio'}</strong><p>{wifiUrl?'La tarjeta abriría el enlace de acceso que configuraste.':'El enlace de acceso todavía no está configurado en esta demo.'}</p><span className="nv4DemoDisabled">Abrir acceso configurado ↗</span></div>}
      {step==='done'&&<div className="nv4DemoSimple"><span className="nv4DemoIcon">✓</span><strong>Ahora ya sabes qué puedes configurar.</strong><p>Al registrarte tendrás acceso al panel real. El recorrido que hiciste aquí no cambió ninguna cuenta.</p></div>}
      <p role="status" className="nv4DemoStatus">{notice}</p><div className="nv4DemoActions">{index>0&&<button type="button" onClick={back}>← Anterior</button>}{index<steps.length-1&&<button type="button" onClick={next}>Siguiente: {labels[steps[index+1]]} →</button>}{step==='done'&&<a href="/auth?mode=signup">Crear mi cuenta →</a>}</div>
    </div></div></div>;
}
