import { redirect } from 'next/navigation';
import Link from 'next/link';
import { createClient } from '@/lib/supabase/server';
import { publicSiteUrl } from '@/lib/payment-profile';
import { PaymentEditor } from './payment-editor';
import { DashboardNavigation } from '../dashboard-navigation';
import { money, NIVAL_PAY_PRICE_CENTS, NIVAL_PAY_ADDITIONAL_PRICE_CENTS, NIVAL_PAY_ADDITIONAL_PRODUCT, NIVAL_PAY_INCLUDED_SECTIONS, NIVAL_PAY_EXTRA_SECTION_PRICE_CENTS, NIVAL_PAY_EXTRA_SECTION_PRODUCT } from '@/lib/orders';
import { PaymentProfileQr } from '../payment-profile-qr';
import { cancelLatestTerminalMercadoPagoProductOrder, reconcileLatestMercadoPagoProductOrder } from '@/lib/reconcile-mercado-pago-order';
import { getActiveBusinessMembership } from '@/lib/active-business';
import { PaymentStatusPoller } from '@/app/checkout/payment-status-poller';

export default async function PaySettings({searchParams}:{searchParams:Promise<{profile?:string;error?:string;view?:string;unlocked?:string;result?:string;created?:string;cash?:string;free?:string}>}){
 const params=await searchParams; const currentView=params.view==='add'?'add':params.view==='share'?'share':'manage';
 const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user)redirect('/auth?next=%2Fdashboard%2Fpay');
 const membership=await getActiveBusinessMembership(user.id); if(!membership)redirect('/dashboard?next=%2Fdashboard%2Fpay'); if(membership.role==='staff')redirect('/dashboard');
 const {data:business,error}=await supabase.from('businesses').select('name,logo_url,brand_color,subscription_status,product_level').eq('id',membership.business_id).maybeSingle(); if(error||!business)throw new Error('No se pudo cargar el negocio.');
 await reconcileLatestMercadoPagoProductOrder(membership.business_id,{[NIVAL_PAY_EXTRA_SECTION_PRODUCT]:NIVAL_PAY_EXTRA_SECTION_PRICE_CENTS,[NIVAL_PAY_ADDITIONAL_PRODUCT]:NIVAL_PAY_ADDITIONAL_PRICE_CENTS});
 if(params.result==='failure')await cancelLatestTerminalMercadoPagoProductOrder(membership.business_id,{[NIVAL_PAY_EXTRA_SECTION_PRODUCT]:NIVAL_PAY_EXTRA_SECTION_PRICE_CENTS,[NIVAL_PAY_ADDITIONAL_PRODUCT]:NIVAL_PAY_ADDITIONAL_PRICE_CENTS});
 if(params.result==='success'&&currentView==='manage'&&params.profile){const {data:r}=await supabase.from('payment_profiles').select('id,custom_sections,extra_sections_purchased').eq('id',params.profile).eq('business_id',membership.business_id).maybeSingle();if(r){const s=Array.isArray(r.custom_sections)?r.custom_sections:[];const limit=NIVAL_PAY_INCLUDED_SECTIONS+Number(r.extra_sections_purchased??0);if(s.length<limit){const next=[...s,{id:crypto.randomUUID(),title:'',content:'',public:true}];const {error:e}=await supabase.from('payment_profiles').update({custom_sections:next,updated_at:new Date().toISOString()}).eq('id',r.id).eq('business_id',membership.business_id);if(!e)redirect(`/dashboard/pay?view=manage&profile=${r.id}&unlocked=1`)}redirect(`/dashboard/pay?view=manage&profile=${r.id}`)}}
 const [{data:paidOrder},{data:profiles,error:profileError}]=await Promise.all([supabase.from('product_orders').select('id').eq('business_id',membership.business_id).in('product_code',['nival_pay','nival_cards_bundle']).eq('status','paid').limit(1).maybeSingle(),supabase.from('payment_profiles').select('id,display_name,account_holder,bank_name,clabe,concept,payment_url,image_url,public_token,active,view_count,clabe_copy_count,last_viewed_at,holder_visible,bank_visible,clabe_visible,concept_visible,payment_url_visible,custom_sections,extra_sections_purchased').eq('business_id',membership.business_id).order('created_at')]);
 if(profileError)throw new Error('No se pudo cargar Nival Pay.'); const profile=profiles?.find(i=>i.id===params.profile)??profiles?.[0]??null;
 const cards=<section className="nivalPayCatalog" aria-label="Tus Nival Pay">{profiles?.map((item,index)=><article className="nivalPayCatalogCard" key={item.id}><Link className="nivalCardDirectLink" href={`/dashboard/pay?profile=${item.id}`} aria-label={`Seleccionar ${item.display_name}`}><div className="nivalPhysicalCard"><div className="nivalCardMark">N</div><div className="nivalCardCopy"><strong>NIVAL</strong><span>PAY {index+1}</span></div><small>PÁGINA DE COBRO</small></div><h2>{item.display_name}</h2><span className="nivalSingleEdit">Editar esta tarjeta →</span></Link></article>)}<article className="nivalPayCatalogCard nivalPayAddCard"><Link className="nivalCardDirectLink" href="/dashboard/cards/add" aria-label="Agregar otra Nival Pay"><div className="nivalAddCardVisual"><span className="nivalAddPlus">+</span><small>NUEVA NIVAL PAY</small></div><h2>Agregar otra Nival Pay</h2><p>Compra y configura una nueva tarjeta desde Comprar Nival Pay.</p><span className="nivalSingleEdit">Agregar Nival Pay →</span></Link></article></section>;
 const isDemo = user.app_metadata?.demo_access === true;
 if(!paidOrder&&!isDemo)return <main className="dashboardApp nivalDashboard"><DashboardNavigation businessName={business.name??'Mi negocio'} active="nival-pay"/><div className="dashboardContent dashboardPayContent"><header className="dashboardContentTopbar payTopbar"><div><strong>Nival Pay</strong></div><span className="ready">Pago único</span></header><section className="dashboardHero"><div><p className="eyebrow">NIVAL PAY</p><h1>Cobra fácil con un solo acceso.</h1><p>Tu tarjeta NFC y página de cobro por {money(NIVAL_PAY_PRICE_CENTS)} MXN. El envío por paquetería se cobra aparte.</p><Link className="nvPrimaryButton" href="/checkout">Comprar mi Nival Pay →</Link></div></section></div></main>;
 const shell=(body:React.ReactNode)=><main className="dashboardApp nivalDashboard">{params.result&&<PaymentStatusPoller active={params.result==='success'||params.result==='pending'}/>}<DashboardNavigation businessName={business.name??'Mi negocio'} active={currentView==='add'?'agregar-tarjetas':currentView==='share'?'compartir-paginas':'nival-pay'}/><div className="dashboardContent dashboardPayContent"><header className="dashboardContentTopbar payTopbar"><div><strong>{currentView==='manage'?'Configurar Nival Pay':currentView==='add'?'Mis Nival Pay':'Compartir Nival Pay'}</strong></div><span className="ready">{isDemo?'Demo privada':'Activo'}</span></header>{params.error&&<p role="alert" className="formMessage errorMessage">{params.error}</p>}{body}</div></main>;
 if(currentView==='add')return shell(<><header className="payHeading payCardsHeading"><p className="eyebrow">MIS NIVAL PAY</p><h1>Selecciona una tarjeta.</h1><p>Toca la Nival Pay que quieras editar. Al entrar al panel se selecciona automáticamente la primera.</p></header>{cards}</>);
 if(currentView==='share')return shell(<><header className="payHeading shareHeading"><p className="eyebrow">COMPARTIR</p><h1>QR, enlace y código de respaldo.</h1><p>Comparte tu Nival Pay. Si el QR no puede escanearse, el cliente puede abrir el enlace escrito.</p></header><section className="sharePagesList sharePagesRefined">{profiles?.map(item=><article className="sharePageItem" key={item.id}><h2>{item.display_name}</h2><PaymentProfileQr businessName={`${business.name??'Nival Pay'}-${item.display_name}`} url={`${publicSiteUrl()}/tap/${item.public_token}`} views={Number(item.view_count)}/></article>)}</section></>);
 return shell(<><header className="payHeading payManageHeading"><p className="eyebrow">EDITAR NIVAL PAY</p><h1>{profile?.display_name??'Tu Nival Pay'}</h1><p>Estás editando esta tarjeta. Para cambiar, elige otra desde «Mis tarjetas».</p>{(profiles?.length??0)>0&&<Link href="/dashboard/pay?view=add" style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:14,width:'100%',marginTop:18,padding:'15px 17px',border:'1px solid #b9d9c6',borderRadius:14,background:'linear-gradient(135deg,#f8fcf9,#edf8f1)',color:'#0d6742',fontWeight:900,fontSize:15}}> <span>▣ &nbsp; Seleccionar otra Nival Pay</span><span aria-hidden="true">→</span></Link>}</header>{['owner','manager'].includes(membership.role)&&profile&&<PaymentEditor key={profile.id} businessId={membership.business_id} businessName={business.name??'Mi negocio'} businessLogo={business.logo_url??null} businessBrandColor={business.brand_color??null} profile={profile} siteUrl={publicSiteUrl()}/>}</>);
}
