import { redirect } from 'next/navigation';
import { FreePaySubmitButton } from "./free-pay-submit-button";
import { createClient } from '@/lib/supabase/server';
import { publicSiteUrl } from '@/lib/payment-profile';
import { PaymentEditor } from './payment-editor';
import { DashboardNavigation } from '../dashboard-navigation';
import { NIVAL_PAY_ADDITIONAL_PRICE_CENTS, NIVAL_PAY_ADDITIONAL_PRODUCT, NIVAL_PAY_INCLUDED_SECTIONS, NIVAL_PAY_EXTRA_SECTION_PRICE_CENTS, NIVAL_PAY_EXTRA_SECTION_PRODUCT } from '@/lib/orders';
import { createAdditionalPaymentProfile, prepareFreeNivalPay, publishFreeNivalPay } from './actions';
import { startAdditionalNivalPayCheckout, requestAdditionalNivalPayCashPayment } from '@/app/checkout/actions';
import { PaymentProfileQr } from '../payment-profile-qr';
import { cancelLatestTerminalMercadoPagoProductOrder, reconcileLatestMercadoPagoProductOrder } from '@/lib/reconcile-mercado-pago-order';
import { getActiveBusinessMembership } from '@/lib/active-business';
import { CheckoutSubmitButton } from '@/app/checkout/submit-button';
import { PaymentStatusPoller } from '@/app/checkout/payment-status-poller';
export default async function PaySettings({searchParams}:{searchParams:Promise<{profile?:string;error?:string;view?:string;unlocked?:string;result?:string;created?:string;cash?:string;free?:string}>}){
 const params=await searchParams;const currentView=params.view==='add'?'add':params.view==='share'?'share':'manage';const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/auth?next=%2Fdashboard%2Fpay');const membership=await getActiveBusinessMembership(user.id);if(!membership)redirect('/dashboard?next=%2Fdashboard%2Fpay');if(membership.role==='staff')redirect('/dashboard/points?view=visits');const {data:business,error}=await supabase.from('businesses').select('name,logo_url,brand_color,subscription_status,product_level,nival_pay_free_enabled,nival_pay_trial_started_at').eq('id',membership.business_id).maybeSingle();if(error||!business)throw new Error('No se pudo cargar el negocio.');await reconcileLatestMercadoPagoProductOrder(membership.business_id,{[NIVAL_PAY_EXTRA_SECTION_PRODUCT]:NIVAL_PAY_EXTRA_SECTION_PRICE_CENTS,[NIVAL_PAY_ADDITIONAL_PRODUCT]:NIVAL_PAY_ADDITIONAL_PRICE_CENTS});if(params.result==='failure')await cancelLatestTerminalMercadoPagoProductOrder(membership.business_id,{[NIVAL_PAY_EXTRA_SECTION_PRODUCT]:NIVAL_PAY_EXTRA_SECTION_PRICE_CENTS,[NIVAL_PAY_ADDITIONAL_PRODUCT]:NIVAL_PAY_ADDITIONAL_PRICE_CENTS});if(params.result==='success'&&currentView==='manage'&&params.profile){const {data:r}=await supabase.from('payment_profiles').select('id,custom_sections,extra_sections_purchased').eq('id',params.profile).eq('business_id',membership.business_id).maybeSingle();if(r){const s=Array.isArray(r.custom_sections)?r.custom_sections:[];const limit=NIVAL_PAY_INCLUDED_SECTIONS+Number(r.extra_sections_purchased??0);if(s.length<limit){const next=[...s,{id:crypto.randomUUID(),title:'',content:'',public:true}];const {error:e}=await supabase.from('payment_profiles').update({custom_sections:next,updated_at:new Date().toISOString()}).eq('id',r.id).eq('business_id',membership.business_id);if(!e)redirect(`/dashboard/pay?view=manage&profile=${r.id}&unlocked=1`)}redirect(`/dashboard/pay?view=manage&profile=${r.id}`)}}if(params.result==='success'&&currentView==='add')await createAdditionalPaymentProfile();
 const [{data:paidOrder},{data:profiles,error:profileError},{count:paidExtras}]=await Promise.all([supabase.from('product_orders').select('id').eq('business_id',membership.business_id).eq('product_code','nival_pay').eq('status','paid').limit(1).maybeSingle(),supabase.from('payment_profiles').select('id,display_name,account_holder,bank_name,clabe,concept,payment_url,image_url,public_token,active,view_count,clabe_copy_count,last_viewed_at,holder_visible,bank_visible,clabe_visible,concept_visible,payment_url_visible,custom_sections,extra_sections_purchased').eq('business_id',membership.business_id).order('created_at'),supabase.from('product_orders').select('id',{count:'exact',head:true}).eq('business_id',membership.business_id).eq('product_code',NIVAL_PAY_ADDITIONAL_PRODUCT).eq('status','paid')]);if(profileError)throw new Error('No se pudo cargar Tocario Pay.');const profile=profiles?.find(i=>i.id===params.profile)??profiles?.[0]??null;const canCreateAdditional=(profiles?.length??0)<1+(paidExtras??0);const freeEnabled=!paidOrder&&Boolean(business.nival_pay_free_enabled);const freeSetup=!paidOrder&&Boolean(profile)&&!freeEnabled;const started=business.nival_pay_trial_started_at?new Date(business.nival_pay_trial_started_at).getTime():null;const days=freeEnabled&&started?Math.max(0,15-Math.floor((Date.now()-started)/86400000)):15;const expired=freeEnabled&&days<=0;
 const cards=<section className="nivalPayCatalog" aria-label="Tus Tocario Pay">{profiles?.map((item,index)=><article className="nivalPayCatalogCard" key={item.id}><a className="nivalCardDirectLink" href={`/dashboard/pay?profile=${item.id}`}><div className="nivalPhysicalCard"><div className="nivalCardMark">T</div><div className="nivalCardCopy"><strong>TOCARIO</strong><span>PAY {index+1}</span></div><small>PÁGINA DE COBRO</small></div></a><h2>{item.display_name}</h2><a href={`/dashboard/pay?profile=${item.id}`}>Configurar →</a></article>)}</section>;
 if(!paidOrder&&!profile)return <main className="dashboardApp nivalDashboard"><DashboardNavigation businessName={business.name??'Mi negocio'} active="nival-pay"/><div className="dashboardContent dashboardPayContent"><header className="dashboardContentTopbar payTopbar"><div><strong>Tocario Pay</strong></div><span className="ready">15 días gratis</span></header><section className="dashboardHero trialHero"><div><p className="eyebrow">TOCARIO PAY</p><h1>Cobra fácil con un solo acceso.</h1><p>Agrega tus datos de cobro. Tu cliente escanea el QR, abre tu Tocario Pay y copia los datos para pagarte.</p><form action={prepareFreeNivalPay}><FreePaySubmitButton/></form></div></section></div></main>;
 const shell=(body:React.ReactNode)=><main className="dashboardApp nivalDashboard">{params.result&&<PaymentStatusPoller active={params.result==='success'||params.result==='pending'}/>}<DashboardNavigation businessName={business.name??'Mi negocio'} active={currentView==='add'?'agregar-tarjetas':currentView==='share'?'compartir-paginas':'nival-pay'}/><div className="dashboardContent dashboardPayContent"><header className="dashboardContentTopbar payTopbar"><div><strong>{currentView==='manage'?'Configurar Tocario Pay':currentView==='add'?'Mis Tocario Pay':'Compartir Tocario Pay'}</strong>{!paidOrder&&<b>{expired?'Prueba terminada':`${days} días gratis restantes`}</b>}</div>{paidOrder?<span className="ready">Pro</span>:<a className="nvPrimaryLink" href="/checkout">Cambiar a Pro</a>}</header>{params.error&&<p role="alert" className="formMessage errorMessage">{params.error}</p>}{body}</div></main>;
 if(currentView==='add')return shell(<><header className="payHeading"><p className="eyebrow">MIS TOCARIO PAY</p><h1>Tus tarjetas Pay.</h1><p>Cada tarjeta tiene sus propios datos, enlace y QR.</p></header>{cards}<section id="agregar-nival-pay" className="nivalAddProduct nivalAddProductSeparate"><div><span>OTRO PUNTO DE COBRO</span><h2>Agregar otra Tocario Pay</h2><p>Crea una Tocario Pay independiente para otra caja, sucursal o uso.</p><strong><s>$199 MXN</s> · $99 MXN</strong></div><div className="nivalAdditionalActions">{!paidOrder?<form action={startAdditionalNivalPayCheckout}><CheckoutSubmitButton className="nvPrimaryButton" pendingLabel="Abriendo Mercado Pago…">Agregar nueva Tocario Pay · $99</CheckoutSubmitButton></form>:canCreateAdditional?<form action={createAdditionalPaymentProfile}><CheckoutSubmitButton className="nvPrimaryButton" pendingLabel="Creando…">Agregar nueva Tocario Pay</CheckoutSubmitButton></form>:<><form action={startAdditionalNivalPayCheckout}><CheckoutSubmitButton className="nvPrimaryButton" pendingLabel="Abriendo Mercado Pago…">Agregar nueva Tocario Pay · $99</CheckoutSubmitButton></form><form action={requestAdditionalNivalPayCashPayment}><CheckoutSubmitButton className="nvSecondaryButton" pendingLabel="Registrando…">Pagar presencialmente · $99</CheckoutSubmitButton></form></>}</div></section></>);
 if(currentView==='share')return shell(<><header className="payHeading shareHeading"><p className="eyebrow">COMPARTIR</p><h1>QR, enlace y código de respaldo.</h1><p>Comparte tu Tocario Pay. Si el QR no puede escanearse, el cliente puede abrir el enlace escrito.</p></header><section className="sharePagesList sharePagesRefined">{profiles?.map(item=><article className="sharePageItem" key={item.id}><h2>{item.display_name}</h2><PaymentProfileQr businessName={`${business.name??'Tocario Pay'}-${item.display_name}`} url={`${publicSiteUrl()}/pay/${item.public_token}`} views={Number(item.view_count)} pro={Boolean(paidOrder)}/></article>)}</section></>);
 return shell(<><header className="payHeading payManageHeading"><p className="eyebrow">CONFIGURAR</p><h1>{profile?.display_name??'Tu Tocario Pay'}</h1><p>1. Agrega tus datos. 2. Guarda los cambios. 3. Ve a «Compartir Tocario Pay» para usar tu QR, enlace o código escrito.</p>{!paidOrder&&<small>{expired?'Tu prueba terminó.':`${days} días gratis restantes.`} <a href="/checkout">Cambiar a Pro →</a></small>}</header>{['owner','manager'].includes(membership.role)&&profile&&<PaymentEditor key={profile.id} businessId={membership.business_id} businessName={business.name??'Mi negocio'} businessLogo={business.logo_url??null} businessBrandColor={business.brand_color??null} profile={profile} siteUrl={publicSiteUrl()} trialMode={!paidOrder}/>} {freeSetup&&profile&&<form action={publishFreeNivalPay} className="trialLaunchBar"><input type="hidden" name="profileId" value={profile.id}/><div><strong>Activa tu acceso.</strong><small>QR, enlace y código durante 15 días.</small></div><button type="submit">Activar prueba →</button></form>}</>);
}
