import Link from 'next/link';
import localFont from 'next/font/local';
import { LandingTabs } from './landing-tabs';
import { pricingV2, previewMxn } from '@/lib/pricing';
import './v2-landing.css';
export const metadata = { title: 'Tocvia | Tarjeta NFC para tu negocio', description: 'Comparte tus datos de pago, tu enlace de reseñas y tu WiFi desde una tarjeta NFC. Mira la demo y empieza una prueba gratuita.' };

const sora = localFont({ src: '../fonts/sora-latin-700.woff2', weight: '700', variable: '--nv2-font-title', display: 'swap' });
const inter = localFont({ src: [{ path: '../fonts/inter-latin-400.woff2', weight: '400' }, { path: '../fonts/inter-latin-700.woff2', weight: '700' }], variable: '--nv2-font-body', display: 'swap' });
const signup = '/auth?mode=signup';
const whatsapp = 'https://wa.me/525539044788?text=' + encodeURIComponent('Hola, quiero conocer las tarjetas NFC de Tocvia.');
const questions = [
  ['¿Necesitan instalar una app?', 'No. El enlace y el QR abren la página desde el navegador.'],
  ['¿Qué pasa si el celular no tiene NFC?', 'El cliente puede escanear el QR o abrir el enlace que le compartas.'],
  ['¿Tocvia recibe mis pagos?', 'No. La página muestra tus datos de transferencia; el dinero va directamente a tu cuenta.'],
  ['¿La tarjeta conecta automáticamente al WiFi?', 'No. Muestra la red y la contraseña para que el cliente las copie.'],
  ['¿Cuándo recibiré la tarjeta física?', 'La fecha y el método de entrega se confirmarán antes de pagar.'],
];
export default function Home() {
  return <main className={`nv2 nv3 ${sora.variable} ${inter.variable}`} id="inicio">
    <nav className="nv2Nav" aria-label="Navegación principal"><a className="nv2Brand" href="#inicio"><span className="nv3BrandMark" aria-hidden="true"><svg viewBox="0 0 40 40" fill="none"><rect x="5" y="6" width="22" height="29" rx="6" stroke="currentColor" strokeWidth="3"/><path d="M13 21c4-6 13-6 17 0m-13 5c3-4 8-4 11 0m-6 5h.1" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/></svg></span>Tocvia</a><div className="nv2NavLinks"><a href="#como-funciona">Cómo funciona</a><a href="#demo">Demo</a><a href="#precios">Precios</a><a href="#preguntas">Preguntas</a></div><div className="nv2NavActions"><Link href="/auth">Entrar</Link><Link className="nv2Button" href={signup}>Empezar gratis</Link></div></nav>
    <section className="nv3Hero"><span className="nv2Eyebrow">UNA TARJETA NFC PARA TU NEGOCIO</span><h1>Un toque.<br/><em>Y ya está.</em></h1><p>Tu cliente abre tus datos de pago, reseñas o WiFi desde una tarjeta. Sin descargar una app.</p><div className="nv3HeroActions"><Link className="nv2Button nv2BigButton" href={signup}>Empezar prueba gratis <span aria-hidden="true">↗</span></Link><Link className="nv2OutlineButton" href="/demo/cards">Ver demo <span aria-hidden="true">↗</span></Link></div><small>Prueba de 15 días · Sin tarjeta bancaria · Planes propuestos desde {previewMxn(pricingV2.cards.essential.priceCents)}</small></section>
    <section className="nv3Showcase" aria-label="Vista de la tarjeta y la página"><div className="nv3ShowcaseHeading"><span>UNA TARJETA. TRES ACCESOS.</span><span>Ejemplo interactivo · datos ficticios</span></div><div className="nv3ShowcaseBody"><div className="nv3Card" aria-label="Representación de una tarjeta NFC Tocvia"><div className="nv3CardTop"><span className="nv3BrandMark">↗</span><b>Tocvia</b></div><div className="nv3CardBottom"><span>ACERCA TU CELULAR</span><svg viewBox="0 0 38 38" fill="none" stroke="currentColor" strokeWidth="2.5" aria-hidden="true"><path d="M10 14c6 2 6 8 0 10m6-15c12 6 12 14 0 20m7-25c17 9 17 21 0 30"/></svg></div></div><div className="nv3ProductPreview"><div className="nv3PreviewTop"><span>9:41</span><span>●●●</span></div><div className="nv3PreviewContent"><span className="nv3PreviewAvatar">T</span><small>TARJETA DE EJEMPLO</small><strong>Tu negocio</strong><p>Elige qué quiere hacer tu cliente</p><div><span>↗&nbsp; Ver datos de pago</span><span>☆&nbsp; Dejar reseña</span><span>⌁&nbsp; Ver WiFi</span></div></div></div></div><Link href="/demo/cards">Toca la demo y mira cada pantalla <span aria-hidden="true">→</span></Link></section>
    <section className="nv2Section nv2Demo" id="demo"><div className="nv2SectionHead"><span className="nv2Eyebrow">ASÍ SE USA</span><h2>Lo que ve tu cliente, sin adivinar.</h2><p>Cambia entre las tres acciones. Las pantallas son ejemplos de producto con datos ficticios.</p></div><LandingTabs/><Link className="nv2TextLink" href="/demo/cards">Abrir demo de Cards en mi celular →</Link></section>
    <section className="nv2Section nv2Before" id="como-funciona"><div className="nv2SectionHead"><span className="nv2Eyebrow">MENOS VUELTAS</span><h2>La información, cuando hace falta.</h2></div><div className="nv2Compare"><article><span>LA CONVERSACIÓN DE SIEMPRE</span><div className="nv2Bubbles"><p>“¿Me pasas tu CLABE?”</p><p>“Espérame, la busco…”</p></div><h3>Buscar, dictar, repetir.</h3></article><article><span>CON TU TARJETA</span><div className="nv2MiniPage"><b>Tu negocio</b><small>Datos de pago · Reseñas · WiFi</small><i>Copiar datos</i></div><h3>Un acceso para compartir.</h3></article></div><div className="nv2Steps"><div><b>01</b><h3>Crea tu cuenta</h3><p>Agrega los datos de tu negocio.</p></div><div><b>02</b><h3>Prueba tu enlace</h3><p>Ábrelo como lo verá tu cliente.</p></div><div><b>03</b><h3>Elige un plan</h3><p>Conserva las acciones que necesites.</p></div><div><b>04</b><h3>Recibe tu tarjeta</h3><p>Compártela cuando esté lista.</p></div></div></section>
    <section className="nv2Section nv2Pricing" id="precios"><div className="nv2SectionHead"><span className="nv2Eyebrow">PLANES TOCVIA</span><h2>Una compra. Tu tarjeta NFC.</h2><p>Estos paquetes todavía no están habilitados para compra. Puedes empezar con una prueba gratis.</p></div><div className="nv2PriceGrid">{[pricingV2.cards.complete,pricingV2.cards.essential].map((plan,i)=><article key={plan.name} className={i===0?'featured':''}><h3>{plan.name}</h3><p>{i===0?'Para compartir tus tres accesos.':'Para empezar con una acción.'}</p><div className="nv2Amount">{previewMxn(plan.priceCents)} <small>pago único propuesto</small></div><ul>{plan.features.map(feature=><li key={feature}><span aria-hidden="true">✓</span>{feature}</li>)}</ul><Link className={i===0?'nv2Button':'nv2OutlineButton'} href={signup}>Empezar prueba gratis</Link><small>Al terminar tu prueba, revisa la opción de compra disponible.</small></article>)}</div><p className="nv2Extras">La compra de estos paquetes no está habilitada todavía. Confirma precio y entrega antes de pagar.</p></section>
    <section className="nv2Section nv2Faq" id="preguntas"><div className="nv2SectionHead"><span className="nv2Eyebrow">PREGUNTAS</span><h2>Antes de empezar</h2></div>{questions.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section>
    <section className="nv2Final"><span>PRUÉBALA TÚ MISMO</span><h2>Acércala a tu negocio.</h2><p>Primero conoce la demo. Luego prepara tu tarjeta en la prueba gratuita.</p><Link className="nv2Button" href="/demo/cards">Ver la demo</Link></section>
    <footer className="nv2Footer"><strong>Tocvia <small>por Nival Tech</small></strong><div><Link href="/privacy">Privacidad</Link><Link href="/terms">Términos</Link><Link href="/cookies">Cookies</Link><Link href="/refunds">Reembolsos</Link><Link href="/auth">Entrar</Link></div></footer>
    <a className="nv2Whatsapp" href={whatsapp} target="_blank" rel="noreferrer" aria-label="Hablar por WhatsApp"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M20.5 11.6a8.5 8.5 0 0 1-12.7 7.3L3.5 20l1.2-4.2a8.5 8.5 0 1 1 15.8-4.2Z"/><path d="M8.4 8.3c.4-.4.8-.3 1.1.2l.7 1.3c.2.3.1.5-.2.8l-.4.4c.6 1.3 1.5 2.1 2.8 2.8l.4-.4c.3-.3.5-.3.8-.2l1.4.7c.4.3.5.7.1 1.1-.5.6-1.2.8-2 .6-2.7-.8-4.6-2.6-5.3-5.2-.3-.9 0-1.6.6-2.1Z"/></svg></a>
  </main>;
}
