import Link from 'next/link';
import localFont from 'next/font/local';
import { LandingTabs } from './landing-tabs';
import { PaymentPageView } from './pay/[token]/payment-page-view';
import './v2-landing.css';
import './landing-refinement.css';
export const metadata={title:'Nival Tech | Tarjetas NFC para negocios desde $99',description:'Cobra por transferencia, consigue reseñas o comparte WiFi con una Nival Card desde $99 MXN.',alternates:{canonical:'/'}};
const sora=localFont({src:'../fonts/sora-latin-700.woff2',weight:'700',variable:'--nv2-font-title',display:'swap'});const inter=localFont({src:[{path:'../fonts/inter-latin-400.woff2',weight:'400'},{path:'../fonts/inter-latin-700.woff2',weight:'700'}],variable:'--nv2-font-body',display:'swap'});const signup='/auth?mode=signup';const whatsapp='https://wa.me/525539044788?text='+encodeURIComponent('Hola, quiero conocer las tarjetas NFC de Nival Tech.');
const questions=[['¿Necesitan instalar una app?','No. El enlace y el QR abren la página desde el navegador.'],['¿Qué pasa si el celular no tiene NFC?','Puede escanear el QR o abrir el enlace.'],['¿Nival Tech recibe mis pagos?','No. Nival Pay muestra tus datos y el dinero va directamente a tu cuenta.'],['¿Puedo probarlo antes de comprar?','Sí. Tienes 15 días de prueba digital antes de pedir la tarjeta física.'],['¿Qué incluye una Nival Card de $99?','Pay, Reseñas o WiFi, su página digital, QR y una tarjeta NFC física.']];
export default function Home(){return <main className={`nv2 nv3 ${sora.variable} ${inter.variable}`} id="inicio"><nav className="nv2Nav"><a className="nv2Brand" href="#inicio"><span className="nv3BrandMark"><svg viewBox="0 0 40 40" fill="none"><rect x="5" y="6" width="22" height="29" rx="6" stroke="currentColor" strokeWidth="3"/><path d="M13 21c4-6 13-6 17 0m-13 5c3-4 8-4 11 0m-6 5h.1" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/></svg></span>Nival Tech</a><div className="nv2NavLinks"><a href="#como-funciona">Cómo funciona</a><a href="#demo">Demo</a><a href="#precios">Precios</a><a href="#preguntas">Preguntas</a></div><div className="nv2NavActions"><Link href="/auth">Entrar</Link></div></nav>
<section className="nv3Hero"><span className="nv2Eyebrow">NIVAL CARD · DESDE $99 MXN</span><h1>Un toque.<br/><em>Y ya está.</em></h1><p>Una tarjeta NFC para que tus clientes puedan pagar por transferencia, dejar una reseña o abrir tu WiFi sin buscar enlaces ni instalar una app.</p><div className="nv3HeroActions"><Link className="nv2Button nv2BigButton" href={signup}>Probar 15 días gratis</Link><Link className="nv2OutlineButton" href="/demo/cards">Ver demo</Link></div><small>Prueba primero la experiencia digital. Compra la tarjeta cuando estés listo.</small></section>
<section className="nv3Showcase"><div className="nv3ShowcaseHeading"><span>ASÍ SE VERÍA TU TARJETA</span><span>Tarjeta NFC · pantalla real de Nival Pay con datos de ejemplo</span></div><div className="nv3ShowcaseBody nv4ShowcaseBody"><div className="nv4CardPhoto"><div className="nv4BrandCard"><strong>Nival Tech</strong><span>)))</span></div></div><div className="nv4PhoneActual"><div className="nv4PhoneStatus">9:41 <span>●●●</span></div><div className="nv4PhoneViewport"><PaymentPageView embedded profile={{business_name:'Tu negocio',brand_color:'#18784c',account_holder:'Nombre de ejemplo',bank_name:'Banco de ejemplo',clabe:'000000000000000000',concept:'Consumo',holder_visible:true,bank_visible:true,clabe_visible:true,concept_visible:true,custom_sections:[]}}/></div></div></div><Link href="/demo/cards">Recorre el panel demo →</Link></section>
<section className="nv2Section nv2Demo" id="demo"><div className="nv2SectionHead"><span className="nv2Eyebrow">PRUÉBALO ANTES DE COMPRAR</span><h2>Ve lo mismo que verías en tu panel.</h2><p>Configura Pay, Reseñas o WiFi y cambia a la vista del cliente.</p></div><LandingTabs/><Link className="nv2TextLink" href="/demo/cards">Abrir panel demo →</Link></section>
<section className="nv2Section nv2Before" id="como-funciona"><div className="nv2SectionHead"><span className="nv2Eyebrow">MENOS VUELTAS</span><h2>Una acción cotidiana, sin buscar enlaces.</h2><p>Tu cliente acerca el celular, abre la acción configurada y continúa desde su teléfono.</p></div><div className="nv2Steps"><div><b>01</b><h3>Crea tu cuenta</h3><p>Configura tu negocio.</p></div><div><b>02</b><h3>Prueba 15 días</h3><p>Míralo como cliente.</p></div><div><b>03</b><h3>Compra desde $99</h3><p>Pay, Reseñas o WiFi.</p></div><div><b>04</b><h3>Diseño y entrega</h3><p>Recibe tu tarjeta NFC.</p></div></div></section>
<section className="nv2Section nv2Pricing" id="precios"><div className="nv2SectionHead"><span className="nv2Eyebrow">PRECIOS CLAROS</span><h2>Empieza con una acción por $99.</h2><p>Pay, Reseñas y WiFi cuestan $99 MXN cada uno. Los tres accesos cuestan $199 MXN.</p></div><div className="nv2PriceGrid"><article className="featured"><h3>Una Nival Card</h3><p>Elige Pay, Reseñas o WiFi.</p><div className="nv2Amount">$99 <small>MXN · pago único</small></div><ul><li><span>✓</span>Una acción</li><li><span>✓</span>Página configurable</li><li><span>✓</span>QR de respaldo</li><li><span>✓</span>Tarjeta NFC física</li></ul><Link className="nv2Button" href={signup}>Probar 15 días gratis</Link></article><article><h3>Paquete completo</h3><p>Pay + Reseñas + WiFi.</p><div className="nv2Amount">$199 <small>MXN · pago único</small></div><ul><li><span>✓</span>Tres accesos</li><li><span>✓</span>Páginas configurables</li><li><span>✓</span>QR de respaldo</li><li><span>✓</span>Tarjeta NFC física</li></ul><Link className="nv2OutlineButton" href={signup}>Probar gratis</Link></article></div></section>
<section className="nv2Section nv2Faq" id="preguntas"><div className="nv2SectionHead"><span className="nv2Eyebrow">PREGUNTAS FRECUENTES</span><h2>Todo claro antes de comprar.</h2></div>{questions.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section><section className="nv2Final"><span>15 DÍAS GRATIS</span><h2>Pruébalo antes de comprar.</h2><div className="nv3HeroActions"><Link className="nv2Button" href={signup}>Probar 15 días gratis</Link><Link className="nv2OutlineButton" href="/demo/cards">Ver demo</Link></div></section><footer className="nv2Footer"><strong>Nival Tech</strong><div><Link href="/privacy">Privacidad</Link><Link href="/terms">Términos</Link><Link href="/cookies">Cookies</Link><Link href="/refunds">Reembolsos</Link></div></footer><a className="nv2Whatsapp" href={whatsapp} target="_blank" rel="noreferrer" aria-label="Hablar por WhatsApp">WhatsApp</a></main>}
