"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { PaymentPageView } from "../pay/[token]/payment-page-view";

type Step = "intro"|"pay-about"|"pay-config"|"pay-use"|"points-about"|"points-config"|"points-use"|"reviews-about"|"reviews-use"|"done";
const steps:Step[]=["intro","pay-about","pay-config","pay-use","points-about","points-config","points-use","reviews-about","reviews-use","done"];

export function DemoFlow(){
 const [step,setStep]=useState<Step>("intro");
 const [business,setBusiness]=useState("Café Nival");
 const [holder,setHolder]=useState("Mariana López");
 const [bank,setBank]=useState("BBVA");
 const [concept,setConcept]=useState("Consumo en Café Nival");
 const [reward,setReward]=useState("Café americano gratis");
 const [points,setPoints]=useState(7); const [redeemed,setRedeemed]=useState(false);
 const index=steps.indexOf(step); const next=()=>setStep(steps[Math.min(index+1,steps.length-1)]); const progress=Math.round(((index+1)/steps.length)*100);
 const clabe=useMemo(()=>"012180001234567897",[]);
 const payProfile=useMemo(()=>({business_name:business||"Tu negocio",business_slug:null,points_enabled:false,logo_url:null,brand_color:"#176b4a",account_holder:holder||"Titular",bank_name:bank||"Banco",clabe,concept:concept||"Pago",payment_url:null,holder_visible:true,bank_visible:true,clabe_visible:true,concept_visible:true,payment_url_visible:false,custom_sections:[{id:"demo-mesa",title:"Referencia",content:"Mesa 08 · Sucursal Roma",public:true}]}),[business,holder,bank,clabe,concept]);
 const pointsReady=points>=10&&!redeemed; const visiblePoints=redeemed?0:Math.min(points,10);
 function addPoint(){if(redeemed)setRedeemed(false);setPoints(v=>Math.min(10,v+1))} function redeem(){setRedeemed(true);setPoints(0)}
 return <main className="guidedDemo"><header className="guidedDemoTop"><Link href="/" className="guidedDemoBrand"><span>N</span><b>Nival Tech</b></Link><div className="guidedDemoProgress"><i style={{width:`${progress}%`}}/></div><small>{index+1} / {steps.length}</small></header><section className="guidedDemoStage">
 {step==="intro"&&<div className="guidedCopy"><span>DEMO INTERACTIVA</span><h1>Prueba Nival como lo usaría un negocio real.</h1><p>Vas a configurar un café de ejemplo, ver la página exacta que abriría un cliente y simular una visita, un pago y una recompensa. Los datos bancarios de esta demo son ficticios.</p><button onClick={next}>Entrar al negocio demo →</button></div>}
 {step==="pay-about"&&<div className="guidedCopy"><span>NIVAL PAY · CAFÉ NIVAL</span><h1>Un cliente acaba de pedir la cuenta.</h1><p>En vez de buscar una CLABE en WhatsApp, ve la Nival Card en caja, acerca su teléfono y abre una página de cobro lista para usar.</p><div className="guidedCardInstructions"><b>Escenario real</b><span>1. Total de la cuenta: $186 MXN.</span><span>2. El cliente acerca el teléfono a la tarjeta.</span><span>3. Copia los datos y hace la transferencia desde su banco.</span></div><button onClick={next}>Configurar lo que verá →</button></div>}
 {step==="pay-config"&&<div className="guidedDemoProductStage"><div className="guidedCopy compact"><span>PANEL DEL NEGOCIO · NIVAL PAY</span><h1>Configura una página de cobro real.</h1><p>Estos son los mismos tipos de datos que llenaría el dueño. Edita cualquier campo y observa el resultado del lado del cliente.</p><div className="guidedInlineFields"><label>Negocio<input value={business} onChange={e=>setBusiness(e.target.value)} maxLength={50}/></label><label>Titular<input value={holder} onChange={e=>setHolder(e.target.value)} maxLength={50}/></label><label>Banco<input value={bank} onChange={e=>setBank(e.target.value)} maxLength={30}/></label><label>Concepto<input value={concept} onChange={e=>setConcept(e.target.value)} maxLength={60}/></label></div><small className="guidedAutosave">✓ Vista previa actualizada en tiempo real · CLABE ficticia para demo</small><button onClick={next}>Ver experiencia del cliente →</button></div><div className="guidedExactPreview"><PaymentPageView profile={payProfile} embedded/></div></div>}
 {step==="pay-use"&&<div className="guidedCopy"><span>CLIENTE · MESA 08</span><h1>La cuenta es de $186 MXN. Ya tiene los datos frente a él.</h1><p className="guidedFlowLead">Esto simula el momento real en caja: el cliente abre Nival Pay, copia la CLABE y cambia a su app bancaria para transferir.</p><div className="guidedTapFlow"><article className="guidedOldWay"><span>SIN NIVAL</span><div className="guidedChat left">“¿Me pasas tu CLABE?”</div><div className="guidedChat right">“Sí, déjame buscarla…”</div><strong>Conversación y espera.</strong></article><div className="guidedFlowArrow">→</div><article className="guidedNewWay"><span>CON NIVAL PAY</span><div className="guidedTapPhone"><small>{business}</small><b>$186 · Mesa 08</b><i>)))</i><button type="button">Copiar CLABE</button><em>✓ Lista para pegar en el banco</em></div><strong>Acerca. Copia. Transfiere.</strong></article></div><button onClick={next}>Siguiente: Nival Puntos →</button></div>}
 {step==="points-about"&&<div className="guidedCopy"><span>NIVAL PUNTOS · SIGUIENTE VISITA</span><h1>Ana volvió al café.</h1><p>Ya es clienta frecuente y tiene 7 de 10 puntos. En caja registras su visita y ella puede ver el progreso desde su tarjeta digital.</p><div className="guidedCardInstructions"><b>Simulación</b><span>1. Ana enseña su QR.</span><span>2. El negocio registra la visita.</span><span>3. Su saldo cambia inmediatamente.</span></div><button onClick={next}>Registrar la visita →</button></div>}
 {step==="points-config"&&<div className="guidedDemoProductStage"><div className="guidedCopy compact"><span>PANEL DEL NEGOCIO · ANA TORRES</span><h1>Registra puntos como si estuvieras en caja.</h1><label className="guidedRewardField">Recompensa<input value={reward} onChange={e=>setReward(e.target.value)} maxLength={60}/></label><div className="guidedPointsActions"><button type="button" onClick={addPoint} disabled={pointsReady}>+ Registrar visita</button>{pointsReady&&<button type="button" className="rewardAction" onClick={redeem}>Canjear recompensa</button>}</div>{redeemed&&<div className="guidedRedeemed"><b>✓ Canje registrado</b><span>{reward}</span></div>}<button onClick={next}>Ver operación completa →</button></div><div className="guidedExactPoints nivalDashboard"><div className="guidedCustomerHint">TELÉFONO DE ANA · VISTA DEL CLIENTE</div><section className="pointsCustomerCard"><div className="pointsCustomerCardTop"><div className="pointsBusinessIdentity"><span>{(business||"N")[0]}</span><div><p className="pointsCustomerProgram">Clientes frecuentes</p><h1>{business}</h1></div></div><span className="pointsCustomerMemberBadge">MIEMBRO</span></div><div className="pointsCustomerGreeting"><span>Hola, Ana</span><small>Tu saldo actual</small></div><div className="pointsBalance"><strong>{visiblePoints}</strong><span>puntos</span></div><div className="pointsProgressBlock"><div className="pointsProgressMeta"><span>Progreso</span><b>{visiblePoints} / 10</b></div><div className="pointsProgress"><i style={{width:`${visiblePoints*10}%`}}/></div></div><div className="pointsReward"><div><span>{pointsReady?"PREMIO DISPONIBLE":"PRÓXIMA RECOMPENSA"}</span><strong>{reward}</strong></div>{pointsReady?<b>Lista para usar</b>:<b>Te faltan {Math.max(0,10-visiblePoints)} puntos</b>}</div></section></div></div>}
 {step==="points-use"&&<div className="guidedCopy"><span>OPERACIÓN EN CAJA</span><h1>El flujo cabe dentro de una venta normal.</h1><div className="guidedUseGrid"><article><b>1</b><strong>Ana muestra su QR</strong><p>El negocio identifica su cuenta.</p></article><article><b>2</b><strong>Registras la visita</strong><p>Un toque suma el punto correspondiente.</p></article><article><b>3</b><strong>Ana ve el cambio</strong><p>Su progreso y recompensa quedan claros en el celular.</p></article></div><button onClick={next}>Siguiente: Nival Reseñas →</button></div>}
 {step==="reviews-about"&&<div className="guidedCopy"><span>NIVAL RESEÑAS · DESPUÉS DE PAGAR</span><h1>Ana terminó contenta con su visita.</h1><p>En vez de pedirle que busque el negocio en Google, acercas la tarjeta de Reseñas y la llevas directamente al lugar donde puede dejar su opinión.</p><div className="guidedCardInstructions"><b>Momento ideal</b><span>1. Termina la compra.</span><span>2. Le pides una reseña si quiere dejarla.</span><span>3. Acerca o escanea y llega a Google.</span></div><button onClick={next}>Simular reseña →</button></div>}
 {step==="reviews-use"&&<div className="guidedSplit"><div className="guidedCopy compact"><span>CLIENTE · GOOGLE</span><h1>El acceso termina donde debe terminar.</h1><div className="guidedUseGrid single"><article><b>1</b><strong>Ana acerca el celular</strong><p>La tarjeta abre el enlace configurado por el negocio.</p></article><article><b>2</b><strong>Google muestra el negocio</strong><p>Sin tener que buscar el nombre manualmente.</p></article><article><b>3</b><strong>Ana decide si publica</strong><p>Nival solo facilita el acceso; la opinión sigue siendo del cliente.</p></article></div></div><div className="guidedReviewCard"><small>Google · {business}</small><span>☆ ☆ ☆ ☆ ☆</span><h2>¿Cómo fue tu experiencia?</h2><p>Comparte una opinión sobre tu visita.</p><button onClick={next}>Simular publicación</button></div></div>}
 {step==="done"&&<div className="guidedCopy"><span>FIN DE LA DEMO</span><h1>Acabas de recorrer una visita completa.</h1><p>Pago en caja, punto de lealtad y acceso a reseñas: la demo usa datos ficticios, pero representa el flujo que vivirían el negocio y sus clientes.</p><Link className="guidedLinkButton" href="/#planes">Ver productos y precios →</Link></div>}
 </section></main>;
}
