import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
import { DashboardNavigation } from '../dashboard-navigation';
import { startNivalIntelligenceSubscription } from '@/app/checkout/actions';
import { reconcileLatestSubscription } from '@/lib/reconcile-subscription';
import { ProductInteractiveDemo } from '../product-interactive-demo';
import styles from './intelligence-dashboard.module.css';

type Visit = { customer_id: string; visited_at: string };

export default async function NivalIntelligencePage({ searchParams }: { searchParams: Promise<{ error?: string; subscription?: string; view?: string }> }) {
  const params = await searchParams;
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect('/auth?next=%2Fdashboard%2Fintelligence');
  const { data: membership } = await supabase.from('business_members').select('business_id, businesses(name, product_level)').eq('user_id', user.id).limit(1).maybeSingle();
  if (!membership) redirect('/dashboard');
  if (params.subscription === 'return') await reconcileLatestSubscription(membership.business_id);
  const business = Array.isArray(membership.businesses) ? membership.businesses[0] : membership.businesses;
  const { data: entitlements } = await supabase.from('business_product_entitlements').select('product_code').eq('business_id', membership.business_id).eq('status', 'active');
  const activeProducts = new Set((entitlements ?? []).map((item) => item.product_code));
  const hasPoints = activeProducts.has('nival_points') || business?.product_level === 'intelligence';
  const active = activeProducts.has('nival_intelligence') || business?.product_level === 'intelligence';
  const view = params.view ?? 'overview';
  const navActive = view === 'risk' ? 'inteligencia-riesgo' : view === 'recurring' ? 'inteligencia-recurrentes' : view === 'campaigns' ? 'inteligencia-campanas' : view === 'impact' ? 'inteligencia-impacto' : view === 'imports' ? 'inteligencia-importar' : view === 'assistant' ? 'inteligencia-asistente' : 'inteligencia';

  const [{ data: customerRows }, { data: visitRows }, { data: rewardRows }] = active ? await Promise.all([
    supabase.from('customers').select('id,name,phone,email,created_at').eq('business_id', membership.business_id).order('created_at',{ascending:false}).limit(500),
    supabase.from('visits').select('customer_id,visited_at').eq('business_id', membership.business_id).order('visited_at',{ascending:false}).limit(5000),
    supabase.from('loyalty_rewards').select('customer_id,redeemed_at').eq('business_id', membership.business_id).limit(3000),
  ]) : [{ data: [] }, { data: [] }, { data: [] }];

  const now = Date.now();
  const day = 86400000;
  const visits = (visitRows ?? []) as Visit[];
  const visitsByCustomer = new Map<string, Visit[]>();
  for (const visit of visits) {
    const bucket = visitsByCustomer.get(visit.customer_id);
    if (bucket) bucket.push(visit); else visitsByCustomer.set(visit.customer_id, [visit]);
  }
  const customers = (customerRows ?? []).map((customer) => {
    const customerVisits = visitsByCustomer.get(customer.id) ?? [];
    const lastVisit = customerVisits[0]?.visited_at ? new Date(customerVisits[0].visited_at) : null;
    const daysSince = lastVisit ? Math.floor((now - lastVisit.getTime()) / day) : null;
    const frequency = customerVisits.length > 1 ? Math.max(1, Math.round((new Date(customerVisits[0].visited_at).getTime() - new Date(customerVisits[customerVisits.length - 1].visited_at).getTime()) / day / (customerVisits.length - 1))) : null;
    return { ...customer, visits: customerVisits.length, lastVisit, daysSince, frequency, status: daysSince === null ? 'Nuevo' : daysSince > 30 ? 'En riesgo' : customerVisits.length >= 3 ? 'Frecuente' : 'Activo' };
  });
  const visits30 = visits.filter((visit) => now - new Date(visit.visited_at).getTime() <= 30 * day).length;
  const previous30 = visits.filter((visit) => { const age = now - new Date(visit.visited_at).getTime(); return age > 30 * day && age <= 60 * day; }).length;
  const change = previous30 ? Math.round(((visits30 - previous30) / previous30) * 100) : visits30 ? 100 : 0;
  const atRisk = customers.filter((customer) => customer.status === 'En riesgo');
  const frequent = customers.filter((customer) => customer.status === 'Frecuente');
  const inactive = customers.filter((customer) => customer.daysSince !== null && customer.daysSince > 60);
  const newCustomers = customers.filter((customer) => customer.visits <= 1);
  const recoverable = atRisk.filter((customer) => customer.daysSince !== null && customer.daysSince <= 60);
  const slipping = customers.filter((customer) => customer.frequency && customer.daysSince !== null && customer.daysSince > customer.frequency * 1.5 && customer.daysSince <= 30);
  const frequentAtRisk = atRisk.filter((customer) => customer.visits >= 3);
  const contactableRisk = recoverable.filter((customer) => customer.phone || customer.email);
  const priorityAudience = frequentAtRisk.length ? frequentAtRisk : recoverable.length ? recoverable : frequent.length ? frequent : newCustomers;
  const priorityContacts = priorityAudience.filter((customer) => customer.phone || customer.email);
  const topPriority = priorityContacts.slice(0, 5);
  const pointsCustomers = customers.filter((customer) => customer.visits >= 2);
  const riskWithHistory = frequentAtRisk.length || recoverable.filter((customer) => customer.visits >= 2).length;
  const priorityLabel = frequentAtRisk.length ? 'clientes frecuentes que se están alejando' : recoverable.length ? 'clientes que puedes recuperar' : frequent.length ? 'clientes frecuentes' : 'clientes nuevos';
  const nextBestAction = frequentAtRisk.length ? 'Recuperarlos antes de ofrecer promociones a clientes nuevos' : recoverable.length ? 'Lanzar una campaña de regreso' : frequent.length ? 'Darles un beneficio exclusivo para reforzar el hábito' : 'Provocar una segunda visita';
  const businessName = business?.name ?? 'nuestro negocio';
  const campaignMessage = recoverable.length
    ? `Hola {{nombre}} 👋 hace rato que no te vemos por ${businessName}. Esta semana queremos consentir a algunos clientes que ya nos conocen. Si te das una vuelta, enséñanos este mensaje y te contamos lo que preparamos para ti. ¿Te vemos pronto?`
    : frequent.length
      ? `Hola {{nombre}} 🙌 nos dimos cuenta de que eres de las personas que más regresan a ${businessName} y queríamos agradecértelo. En tu próxima visita queremos tener un detalle contigo. Cuando vengas, enséñanos este mensaje 😊`
      : `Hola {{nombre}} 👋 gracias por haber venido a ${businessName}. Nos dio gusto recibirte. Si vuelves esta semana, dinos que recibiste este mensaje; queremos darte una buena razón para que esta no sea tu única visita 😊`;
  const alternateMessage = recoverable.length
    ? `Hola {{nombre}}, ¿cómo estás? Hace un rato que no coincides con nosotros en ${businessName} y queríamos invitarte a volver. Si tienes chance esta semana, nos encantará verte otra vez 🙌`
    : frequent.length
      ? `{{nombre}}, gracias por seguir regresando a ${businessName} ❤️ clientes como tú son los que hacen crecer el negocio. Queremos agradecerte en tu próxima visita.`
      : `Hola {{nombre}} 😊 ¿cómo te fue en tu primera visita a ${businessName}? Nos gustaría verte otra vez. Si vuelves pronto, cuéntanos que recibiste este mensaje.`;
  const activeCustomers = customers.filter((customer) => customer.daysSince !== null && customer.daysSince <= 30).length;
  const availableRewards = (rewardRows ?? []).filter((reward) => !reward.redeemed_at).length;
  const retention = customers.length ? Math.round((customers.filter(c => c.visits >= 2).length / customers.length) * 100) : 0;
  const dataCoverage = customers.length ? Math.round((customers.filter(c => c.phone || c.email).length / customers.length) * 100) : 0;
  const intelligenceScore = Math.min(100, Math.round((Math.min(customers.length, 50) / 50) * 35 + (Math.min(visits.length, 150) / 150) * 35 + (dataCoverage / 100) * 30));
  const mainAdvice = atRisk.length ? `${atRisk.length} clientes necesitan atención antes de enfriarse más.` : visits30 ? 'Tu actividad reciente es estable. Conviene reforzar a tus clientes frecuentes.' : 'Registra visitas para que Intelligence encuentre oportunidades reales.';

  return <main className="dashboardApp nivalDashboard">
    <DashboardNavigation businessName={business?.name ?? 'Tu negocio'} active={navActive} />
    <div className={`dashboardContent ${!active ? 'nivalIntelligenceDark' : ''}`}>
      <header className="dashboardContentTopbar"><div><span>Nival Intelligence</span><b>Decisiones basadas en tus datos</b></div><span className="ready">{active ? 'Activo' : hasPoints ? '$449/mes' : '$399/mes'}</span></header>
      {params.error && <p className="formMessage errorMessage">{params.error}</p>}
      {params.subscription && <p className="formMessage">Estamos confirmando tu suscripción con Mercado Pago.</p>}
      {!active ? <>
        <section className="productShowcase intelligenceShowcase"><div className="productShowcaseCopy"><span className="productPill">NIVAL INTELLIGENCE</span><h1>Descubre qué hacer<br/>para vender más.</h1><p>Nival Intelligence revisa la actividad de tu negocio y te explica qué está pasando, qué clientes necesitan atención y cuál es la siguiente acción recomendable.</p><ul className="productBenefits"><li>Detecta clientes en riesgo y recurrentes</li><li>Convierte actividad en métricas claras</li><li>Recomienda acciones concretas</li></ul><div className="productPrice"><strong>{hasPoints ? '$449' : '$399'}</strong><span>MXN al mes</span></div><form action={startNivalIntelligenceSubscription}><button className="productCta">{hasPoints ? 'Activar Puntos + Intelligence' : 'Comenzar con Intelligence'} <span>→</span></button></form></div><div className="intelligenceVisual"><div className="aiGlow"/><div className="aiPanel"><div className="aiPanelTop"><b>NIVAL <em>INTELLIGENCE</em></b><span>EN VIVO</span></div><div className="aiInsight"><small>OPORTUNIDAD DETECTADA</small><strong>24 clientes están cerca de volver a comprar.</strong><p>Una campaña de regreso esta semana podría aumentar la recurrencia.</p></div><div className="aiMiniGrid"><div><small>CLIENTES ACTIVOS</small><b>184</b><i>+12%</i></div><div><small>RECURRENCIA</small><b>38%</b><i>+6.4%</i></div></div></div></div></section>
        <section className="productFeatureStrip darkFeatureStrip"><article><span>01</span><div><b>Todo conectado</b><p>Pay, Puntos, clientes, visitas y actividad en una sola lectura.</p></div></article><article><span>02</span><div><b>Encuentra oportunidades</b><p>Detecta cambios de comportamiento y clientes en riesgo.</p></div></article><article><span>03</span><div><b>Sabe qué hacer después</b><p>Convierte la información en recomendaciones concretas.</p></div></article></section>
        <ProductInteractiveDemo mode="intelligence" />
      </> : <div className={styles.shell}>
        {view === 'overview' && <>
          <section className={styles.solutionHero}><div><span className={styles.eyebrow}>NIVAL INTELLIGENCE · PLAN DE ACCIÓN</span><h1>{recoverable.length ? `Hoy puedes intentar recuperar ${recoverable.length} clientes.` : frequent.length ? `Hoy puedes fortalecer a ${frequent.length} clientes frecuentes.` : 'Hoy toca convertir visitas en clientes que regresan.'}</h1><p>Nival ya revisó clientes, visitas, recurrencia y señales de abandono. Tu trabajo aquí no es analizar: es decidir si quieres aplicar la solución.</p><div className={styles.decisionLine}><span>MEJOR SIGUIENTE ACCIÓN</span><strong>{nextBestAction}</strong><small>{priorityContacts.length} de {priorityAudience.length} clientes objetivo tienen contacto disponible</small></div></div><div className={styles.solutionImpact}><small>OBJETIVO</small><strong>{recoverable.length ? 'Recuperar' : frequent.length ? 'Fidelizar' : 'Repetir'}</strong><span>{recoverable.length || frequent.length || newCustomers.length} clientes detectados</span></div></section>
          <section className={styles.actionMission}>
            <div className={styles.missionHeader}><div><span className={styles.label}>MISIÓN DE HOY · PRIORIZADA POR NIVAL</span><h2>{recoverable.length ? 'Trae de vuelta a clientes que ya te conocen' : frequent.length ? 'Haz que tus mejores clientes se sientan reconocidos' : 'Consigue la segunda visita'}</h2></div><span className={styles.timePill}>≈ 5 min</span></div>
            <div className={styles.missionFlow}>
              <article><span className={styles.step}>1 · NIVAL ENCONTRÓ</span><strong>{recoverable.length || frequent.length || newCustomers.length}</strong><h3>{recoverable.length ? 'clientes recuperables' : frequent.length ? 'clientes frecuentes' : 'clientes nuevos'}</h3><p>{recoverable.length ? 'Ya compraron antes y llevan entre 31 y 60 días sin volver.' : frequent.length ? 'Ya demostraron recurrencia. Son los clientes que más conviene cuidar.' : 'Solo han registrado una visita. El objetivo es provocar la segunda.'}</p><a href="/dashboard/intelligence?view=customers">Ver exactamente quiénes son →</a></article>
              <article className={styles.messageCard}><span className={styles.step}>2 · NIVAL PROPONE</span><h3>Envía este mensaje</h3><blockquote>“{campaignMessage}”</blockquote><div className={styles.personalizationPreview}><small>ASÍ LO PERSONALIZA NIVAL</small><div><span>Nombre</span><b>{priorityContacts[0]?.name ?? '{{nombre}}'}</b></div><div><span>Relación</span><b>{frequentAtRisk.length ? 'Era frecuente' : recoverable.length ? 'Ya te conoce' : frequent.length ? 'Cliente recurrente' : 'Primera visita'}</b></div><div><span>Momento</span><b>{priorityContacts[0]?.daysSince ? `${priorityContacts[0].daysSince} días sin volver` : 'Según su actividad'}</b></div></div><div className={styles.messageWhy}><span>PERSONALIZA</span><p>Reemplaza <b>{'{{nombre}}'}</b> por el nombre del cliente y, si puedes, agrega un beneficio real o una referencia que tenga sentido para tu negocio.</p></div><details className={styles.altMessage}><summary>Ver otra versión</summary><p>“{alternateMessage}”</p></details><div className={styles.channelHint}>Pensado para sonar como un mensaje del negocio, no como publicidad masiva.</div></article>
              <article><span className={styles.step}>3 · NIVAL MEDIRÁ</span><h3>¿Funcionó?</h3><p>Cuando vuelvan a registrar una visita, Nival podrá reconocer el regreso y usar ese resultado para mejorar la siguiente estrategia.</p><div className={styles.outcome}><strong>{retention}%</strong><span>de tus clientes actuales ya han regresado al menos una vez</span></div></article>
            </div>
          </section>
          <section className={styles.priorityPeople}><div className={styles.sectionIntro}><span className={styles.label}>NO BUSQUES EN UNA TABLA</span><h2>Nival ya eligió por dónde empezar</h2></div>{topPriority.length ? <div className={styles.peopleStrip}>{topPriority.map((customer, index)=><article key={customer.id}><span>#{index + 1}</span><div><strong>{customer.name}</strong><small>{customer.visits} visitas · {customer.daysSince ?? 0} días sin volver</small></div><b>{customer.phone ? 'WhatsApp / teléfono' : 'Correo'}</b></article>)}</div> : <div className={styles.emptyAction}>Todavía no hay clientes con contacto dentro de la audiencia prioritaria. Nival seguirá buscando oportunidades conforme se registren visitas.</div>}</section>
          <section className={styles.ownerQuestions}><div><span className={styles.label}>RESPUESTAS RÁPIDAS</span><h2>Lo que un dueño necesita saber</h2></div><div className={styles.questionGrid}><a href="/dashboard/intelligence?view=risk"><small>¿A QUIÉN ESTOY PERDIENDO?</small><strong>{atRisk.length ? `${atRisk.length} clientes necesitan atención` : 'No detectamos pérdidas urgentes'}</strong><span>Nival prioriza quién vale la pena recuperar.</span></a><a href="/dashboard/intelligence?view=recurring"><small>¿A QUIÉN DEBO CUIDAR?</small><strong>{frequent.length ? `${frequent.length} clientes ya son recurrentes` : 'Aún formando recurrencia'}</strong><span>Convierte buenos clientes en hábito.</span></a><a href="/dashboard/intelligence?view=campaigns"><small>¿QUÉ PROMOCIÓN HAGO?</small><strong>{recoverable.length ? 'Campaña de regreso' : frequent.length ? 'Beneficio VIP' : 'Campaña de segunda visita'}</strong><span>La estrategia cambia según el problema detectado.</span></a><a href="/dashboard/intelligence?view=impact"><small>¿ESTÁ FUNCIONANDO?</small><strong>{retention}% de recurrencia observada</strong><span>Revisa resultados, no solo actividad.</span></a></div></section>
          <section className={styles.nextActions}><div className={styles.sectionIntro}><span className={styles.label}>DESPUÉS DE ESO</span><h2>Nival ya encontró las siguientes acciones</h2></div>
            <div className={styles.solutionCards}>
              <a href="/dashboard/intelligence?view=customers"><small>RECUPERAR</small><strong>{frequentAtRisk.length ? `${frequentAtRisk.length} clientes valiosos se están alejando` : `${contactableRisk.length} clientes en riesgo tienen contacto`}</strong><span>{frequentAtRisk.length ? 'Prioriza a quienes antes regresaban seguido.' : 'Ya puedes contactarlos sin revisar toda tu base.'}</span><b>Resolver →</b></a>
              <a href="/dashboard/intelligence?view=opportunities"><small>ANTICIPAR</small><strong>{slipping.length ? `${slipping.length} clientes rompieron su hábito` : 'Sin hábitos rotos detectados'}</strong><span>{slipping.length ? 'Nival los detectó antes de que se vuelvan inactivos.' : 'Seguiremos vigilando la frecuencia automáticamente.'}</span><b>Ver señal →</b></a>
              <a href="/dashboard/intelligence?view=customers"><small>FIDELIZAR</small><strong>{frequent.length ? `${frequent.length} clientes merecen trato especial` : 'Aún construyendo clientes frecuentes'}</strong><span>{frequent.length ? 'Crea una razón para que mantengan su hábito.' : 'Nival detectará este grupo conforme regresen.'}</span><b>Ver clientes →</b></a>
            </div>
          </section>
          <section className={styles.backgroundSignals}><div><span>En riesgo</span><b>{atRisk.length}</b></div><div><span>Frecuentes</span><b>{frequent.length}</b></div><div><span>Inactivos</span><b>{inactive.length}</b></div><div><span>Nuevos</span><b>{newCustomers.length}</b></div><p>Estas cifras alimentan las soluciones de arriba. No necesitas analizarlas para usar Intelligence.</p></section>
        </>}
        {view === 'risk' && <section className={styles.solutionWorkspace}><div className={styles.workspaceHero}><span className={styles.label}>RECUPERAR CLIENTES</span><h1>{recoverable.length ? `Nival encontró ${recoverable.length} clientes que vale la pena intentar recuperar.` : 'No hay clientes en una ventana clara de recuperación.'}</h1><p>{recoverable.length ? 'No te damos una lista para que tú inventes la estrategia. Nival separa a quién contactar, qué decir y qué resultado buscar.' : 'Seguiremos vigilando automáticamente cuándo un cliente rompe su ritmo o deja de regresar.'}</p></div><div className={styles.recoverySummary}><div><small>INTENTAR RECUPERAR</small><strong>{frequentAtRisk.length || recoverable.length}</strong><span>{priorityLabel}</span></div><div><small>PUEDES CONTACTAR HOY</small><strong>{priorityContacts.length}</strong><span>con teléfono o correo</span></div><div><small>PRIORIDAD</small><strong>{frequentAtRisk.length ? 'Alta' : recoverable.length ? 'Media' : 'Sin alerta'}</strong><span>{frequentAtRisk.length ? 'eran clientes frecuentes' : 'según comportamiento actual'}</span></div></div><div className={styles.peopleStrip}>{topPriority.length ? topPriority.map((customer,index)=><article key={customer.id}><span>#{index+1}</span><div><strong>{customer.name}</strong><small>{customer.visits} visitas · {customer.daysSince ?? 0} días sin volver</small></div><b>{customer.phone ? 'Contactar' : 'Correo'}</b></article>) : <div className={styles.emptyAction}>Sin clientes contactables en este segmento.</div>}</div><div className={styles.playbook}><article><small>POR QUÉ ELLOS</small><strong>{frequentAtRisk.length || recoverable.length}</strong><h3>{frequentAtRisk.length ? 'Primero: clientes que antes eran frecuentes' : 'Clientes entre 31 y 60 días sin volver'}</h3><p>Son más valiosos que empezar desde cero porque ya conocen el negocio.</p></article><article className={styles.messageCard}><small>ACCIÓN RECOMENDADA</small><h3>Campaña de regreso</h3><blockquote>“{campaignMessage}”</blockquote><p>Personaliza {'{{nombre}}'} y el beneficio antes de enviarlo. La idea es que parezca escrito por el negocio, no por una plataforma.</p><details className={styles.altMessage}><summary>Alternativa más corta</summary><p>“{alternateMessage}”</p></details></article><article><small>ÉXITO =</small><h3>Que vuelvan a visitar</h3><p>Nival comparará sus próximas visitas para que la siguiente recomendación se base en resultados, no intuición.</p></article></div></section>}
        {view === 'recurring' && <section className={styles.solutionWorkspace}><div className={styles.workspaceHero}><span className={styles.label}>FIDELIZAR RECURRENTES</span><h1>{frequent.length ? `Tienes ${frequent.length} clientes que ya demostraron que regresan.` : 'Todavía no hay suficientes clientes recurrentes.'}</h1><p>La solución no es enseñar una tabla: es decirte cómo proteger a tus mejores clientes antes de perderlos.</p></div><div className={styles.playbook}><article><small>QUÉ HACER</small><h3>Trátalos distinto al resto</h3><p>Prueba un beneficio exclusivo, recompensa anticipada o una experiencia especial para mantener el hábito.</p></article><article><small>NIVAL PUNTOS</small><h3>{hasPoints ? 'Úsalo para reforzar recurrencia' : 'Conecta lealtad con Intelligence'}</h3><p>{hasPoints ? `Nival detecta ${pointsCustomers.length} clientes con 2+ visitas y ${availableRewards} recompensas disponibles. Úsalas con quienes ya muestran hábito, no como descuento indiscriminado.` : 'Con Puntos, Intelligence puede observar visitas y recompensas para entender mejor quién está regresando.'}</p></article><article><small>SEÑAL ACTUAL</small><strong>{retention}%</strong><h3>recurrencia observada</h3><p>Porcentaje de clientes registrados que ya acumulan dos o más visitas.</p></article></div></section>}
        {view === 'campaigns' && <section className={styles.solutionWorkspace}><div className={styles.workspaceHero}><span className={styles.label}>CAMPAÑAS RECOMENDADAS</span><h1>No promociones para todos. Una estrategia para cada problema.</h1><p>Nival propone campañas según el comportamiento que detecta y te explica a quién aplicarlas.</p></div><div className={styles.campaignDecision}><span>NIVAL RECOMIENDA EMPEZAR POR</span><strong>{recoverable.length ? 'Campaña de recuperación' : frequent.length ? 'Beneficio VIP' : 'Segunda visita'}</strong><p>{nextBestAction}. Empieza con una sola estrategia, mide el resultado y después escala.</p></div><div className={styles.campaignGrid}><article><small>RECUPERACIÓN</small><h3>“Te extrañamos”</h3><p>Para {recoverable.length} clientes con 31–60 días sin volver.</p><b>{recoverable.length ? 'Recomendada ahora' : 'Sin audiencia suficiente'}</b></article><article><small>FIDELIZACIÓN</small><h3>Beneficio VIP</h3><p>Para {frequent.length} clientes con recurrencia alta.</p><b>{frequent.length ? 'Lista para probar' : 'Aún formando audiencia'}</b></article><article><small>SEGUNDA VISITA</small><h3>Vuelve esta semana</h3><p>Para {newCustomers.length} clientes con 0–1 visitas.</p><b>{newCustomers.length ? 'Oportunidad detectada' : 'Sin audiencia'}</b></article><article><small>PREVENCIÓN</small><h3>Antes de que se vaya</h3><p>Para {slipping.length} clientes que se retrasaron frente a su frecuencia habitual.</p><b>{slipping.length ? 'Señal temprana detectada' : 'Sin alerta ahora'}</b></article></div></section>}
        {view === 'impact' && <section className={styles.solutionWorkspace}><div className={styles.workspaceHero}><span className={styles.label}>RESULTADOS E IMPACTO</span><h1>¿Lo que hiciste con Nival trajo clientes de vuelta?</h1><p>Aquí solo mostramos resultados que podemos respaldar. La meta es que cada recomendación termine respondiendo tres cosas: cuántos regresaron, cuánto generaron y qué conviene hacer después.</p></div><div className={styles.impactGrid}><article><small>RECURRENCIA OBSERVADA</small><strong>{retention}%</strong><p>Clientes registrados con dos o más visitas.</p></article><article><small>VISITAS · 30 DÍAS</small><strong>{visits30}</strong><p>{previous30 ? `${change >= 0 ? '+' : ''}${change}% frente a los 30 días anteriores.` : 'Aún sin periodo anterior comparable.'}</p></article><article><small>CLIENTES ACTIVOS</small><strong>{activeCustomers}</strong><p>Con una visita registrada en los últimos 30 días.</p></article></div><div className={styles.impactRoadmap}><div><span>1</span><b>Nival recomienda</b><small>Una campaña y audiencia concretas.</small></div><div><span>2</span><b>El negocio la aplica</b><small>Guardamos a quién se dirigió y cuándo.</small></div><div><span>3</span><b>Nival observa</b><small>Detectamos quién regresó después.</small></div><div><span>4</span><b>Nival aprende</b><small>Comparamos estrategias y recomendamos la siguiente.</small></div></div><div className={styles.attributionNotice}><b>Retorno después de campañas y dinero generado</b><p>Para mostrar “X% regresó después de la campaña” y “esto representó $Y”, necesitamos registrar qué campaña se aplicó, a qué clientes y conectar el valor de sus compras. Ese seguimiento será la base para que Intelligence mida ROI real en vez de atribuir ventas sin evidencia.</p></div></section>}
        {view === 'imports' && <><section className={styles.panel}><div className={styles.importBox}><div><span className={styles.label}>CENTRO DE IMPORTACIÓN</span><h2>Trae tus clientes sin capturarlos uno por uno</h2><p>Se preparó el flujo para Excel, CSV y bases exportadas. La validación y el guardado seguro serán el siguiente paso técnico.</p></div><div className={styles.importButtons}><span>Excel .xlsx</span><span>CSV</span><span>Registro manual</span></div></div></section><section className={styles.tools}><article className={`${styles.tool} ${styles.disabled}`}><b>1. Sube tu archivo</b><p>Selecciona una hoja con nombre y al menos un dato de contacto.</p><span>Interfaz preparada</span></article><article className={`${styles.tool} ${styles.disabled}`}><b>2. Revisa las columnas</b><p>Relaciona nombre, teléfono, correo y fecha de última visita.</p><span>Próximo paso</span></article><article className={`${styles.tool} ${styles.disabled}`}><b>3. Confirma la importación</b><p>Detecta duplicados antes de guardar nuevos clientes.</p><span>Próximo paso</span></article></section></>}
        {view === 'assistant' && <section className={styles.grid}><article className={styles.panel}><div className={styles.panelHeader}><div><span className={styles.label}>ASISTENTE NIVAL</span><h2>Pregunta con base en la actividad del negocio</h2></div></div><p className={styles.muted}>Ejemplos: “¿Cuántos clientes están en riesgo?”, “¿Quiénes vienen más veces al mes?” o “¿Qué debería hacer hoy?”.</p><div className={styles.chat}><input aria-label="Pregunta para el asistente" placeholder="Escribe una pregunta sobre tu negocio" disabled/><button type="button" disabled>Preguntar</button></div><p className={styles.sourceNote}>La interfaz está lista. Aún no responde para no simular una IA sin conexión segura a tus datos.</p></article><aside className={styles.panel}><span className={styles.label}>DATOS DISPONIBLES</span><div className={styles.segments}><div className={styles.segment}><span>Clientes</span><b>{customers.length}</b></div><div className={styles.segment}><span>Visitas</span><b>{visits.length}</b></div><div className={styles.segment}><span>Recompensas</span><b>{(rewardRows ?? []).length}</b></div></div></aside></section>}
      </div>}
    </div>
  </main>;
}
